trigger:
- DNFDevelop

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
    displayName: 'Install Node.js'

- script: |
    npm cache clean --force
    rm -rf node_modules
    npm install @auth0/auth0-angular@1.5.0 --legacy-peer-deps
    npm install @spartacus/organization --legacy-peer-deps
    npm install -g @angular/cli
    npm install @types/selenium-webdriver@2.53.36 --legacy-peer-deps
    npm install i18next-resources-to-backend --legacy-peer-deps
    npm install @fontsource/open-sans --legacy-peer-deps
    npm install @fortawesome/fontawesome-free --legacy-peer-deps
    npm install --legacy-peer-deps
    ng build --configuration=dev

- task: Docker@2
  inputs:
    containerRegistry: 'rcfb-acr-fi-dev1-tst'
    repository: 'fi'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'DNFDev'
